version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: on-failure
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - default

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: on-failure
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - default

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: mymongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mymongopassword
    volumes:
      - mongo-data:/data/db
      - mongo-config-data:/data/configdb
    networks:
      - default

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mymongoadmin:mymongopassword@mongodb:27017/?authSource=admin"
      ME_CONFIG_BASICAUTH: "false"
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs-app
    restart: on-failure
    depends_on:
      - kafka
      - kafka-ui
      - mongodb
      - mongo-express
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CONSUMER_GROUP_ID=javan-group
      - NODE_ENV=development
      - MONGO_URI=mongodb://mymongoadmin:mymongopassword@mongodb:27017/mydb?authSource=admin
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules
    command: pnpm run start:dev:ts
    networks:
      - default

volumes:
  kafka-data:
  app_node_modules:
  mongo-data:
  mongo-config-data:

networks:
  default:
    name: kafka-net
